version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} script
           bash kernel_xiaomi_lavender/.circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
