version: 2.1
jobs:
  compile:
   docker:
      - image: ABHI/XXY:latest
   steps:
      - run:
          command: |
           git config --global color.ui false
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} lavender
           bash lavender/circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
