version: 1.1
jobs:
  compile:
   docker:
      - image: abhi/test:latest
   steps:
      - run:
          command: |
           git config --global user.name "sohamxda7"
           git config --global user.email "sensoham135@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh
workflows:
  version: 1.1
  cooking:
    jobs:
      - compile